# Writes kamal config into the app repo and runs deploys in a visible
# "<app>--deploy" tmux session, so the whole deploy is watchable from the browser.
module Production
  module_function

  def launch_deploy(app)
    write_config(app)
    Factory.clean_tmux!
    full = "#{app.name}--deploy"
    system("tmux", "kill-session", "-t", full, err: File::NULL)
    system("tmux", "new-session", "-d", "-s", full, "-c", app.path, *env_flags(app))
    TmuxSession.style(full)
    command = app.deployed_at? ? "bin/kamal deploy" : "bin/kamal setup"
    system("tmux", "send-keys", "-t", full, command, "Enter")
    app.update!(deployed_at: Time.current)
  end

  def write_config(app)
    File.write(File.join(app.path, "config/deploy.yml"), deploy_yaml(app))
    FileUtils.mkdir_p(File.join(app.path, ".kamal"))
    File.write(File.join(app.path, ".kamal/secrets"), SECRETS)
    # kamal builds from git HEAD — uncommitted config would be ignored
    system("git", "-C", app.path, "add", "config/deploy.yml", ".kamal/secrets")
    system("git", "-C", app.path, "commit", "-q", "-m", "Update kamal config (rails-app-factory)")
  end

  # Values resolve from the deploy tmux session's env; file itself holds no secrets.
  SECRETS = <<~EOS
    RAILS_MASTER_KEY=$(cat config/master.key)
    S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
    S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
    LITESTREAM_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
    LITESTREAM_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
  EOS

  def deploy_yaml(app)
    lines = []
    lines << "# Generated by rails-app-factory — overwritten on every deploy."
    lines << "service: #{app.name}"
    lines << "image: #{app.name}"
    lines << "servers:\n  web:\n    - #{app.prod_server}"
    lines << "proxy:\n  ssl: true\n  host: #{app.prod_host}"
    # kamal spins up a throwaway registry on this port and tunnels it over ssh
    lines << "registry:\n  server: localhost:5555"
    lines << "builder:\n  arch: amd64"

    if app.backups_configured?
      lines << "env:\n  secret:\n    - RAILS_MASTER_KEY\n    - S3_ACCESS_KEY_ID\n    - S3_SECRET_ACCESS_KEY\n" \
               "  clear:\n    SOLID_QUEUE_IN_PUMA: true\n    S3_BUCKET: #{app.s3_bucket}\n" \
               "    S3_REGION: #{app.s3_region_or_default}\n    S3_ENDPOINT: #{app.s3_endpoint_or_default}"
    else
      lines << "env:\n  secret:\n    - RAILS_MASTER_KEY\n  clear:\n    SOLID_QUEUE_IN_PUMA: true"
    end

    lines << %(volumes:\n  - "#{app.name}_storage:/rails/storage")
    lines << "asset_path: /rails/public/assets"

    if app.backups_configured?
      lines << <<~ACC.rstrip
        accessories:
          litestream:
            image: litestream/litestream:0.3
            roles:
              - web
            volumes:
              - "#{app.name}_storage:/rails/storage"
            files:
              - config/litestream.yml:/etc/litestream.yml
            cmd: replicate
            env:
              secret:
                - LITESTREAM_ACCESS_KEY_ID
                - LITESTREAM_SECRET_ACCESS_KEY
              clear:
                LITESTREAM_BUCKET: #{app.s3_bucket}
                LITESTREAM_REGION: #{app.s3_region_or_default}
                LITESTREAM_ENDPOINT: #{app.s3_endpoint_or_default}
      ACC
    end

    lines.join("\n\n") + "\n"
  end

  def env_flags(app)
    return [] unless app.backups_configured?
    app.s3_env.flat_map { |key, value| ["-e", "#{key}=#{value}"] }
  end
end
