# Writes kamal config into the app repo and runs deploys in a visible
# "<app>--deploy" tmux session, so the whole deploy is watchable from the browser.
module Production
  module_function

  def launch_deploy(app)
    write_config(app)
    Factory.clean_tmux!
    full = "#{app.name}--deploy"
    system("tmux", "kill-session", "-t", full, err: File::NULL)
    system("tmux", "new-session", "-d", "-s", full, "-c", app.path, *env_flags(app))
    TmuxSession.style(full)
    system("tmux", "send-keys", "-t", full, deploy_command(app), "Enter")
    app.update!(deployed_at: Time.current)
  end

  # Behind the box's own Caddy (APPSMOOTHLY_DOMAIN set) kamal-proxy must leave 80/443
  # to Caddy — pin it to loopback:8080 once, before the first boot.
  BOOT_CONFIG = "bin/kamal proxy boot_config set --publish-host-ip 127.0.0.1 --http-port 8080 --https-port 8443"

  def deploy_command(app)
    return "bin/kamal deploy" if app.deployed_at?
    Factory.domain ? "#{BOOT_CONFIG} && bin/kamal setup" : "bin/kamal setup"
  end

  def write_config(app)
    File.write(File.join(app.path, "config/deploy.yml"), deploy_yaml(app))
    FileUtils.mkdir_p(File.join(app.path, ".kamal"))
    File.write(File.join(app.path, ".kamal/secrets"), SECRETS)
    # kamal builds from git HEAD — uncommitted config would be ignored
    system("git", "-C", app.path, "add", "config/deploy.yml", ".kamal/secrets")
    system("git", "-C", app.path, "commit", "-q", "-m", "Update kamal config (appsmoothly)")
  end

  # Values resolve from the deploy tmux session's env; file itself holds no secrets.
  SECRETS = <<~EOS
    RAILS_MASTER_KEY=$(cat config/master.key)
    S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
    S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
    LITESTREAM_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
    LITESTREAM_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
    SMTP_PASSWORD=$SMTP_PASSWORD
  EOS

  # Provisioned boxes carry a per-customer SMTP credential (Mailgun, via appsmoothly-infra).
  def smtp_clear_env
    return {} if ENV["APPSMOOTHLY_SMTP_ADDRESS"].blank?
    { "SMTP_ADDRESS" => ENV["APPSMOOTHLY_SMTP_ADDRESS"], "SMTP_PORT" => ENV.fetch("APPSMOOTHLY_SMTP_PORT", "587"),
      "SMTP_USER_NAME" => ENV["APPSMOOTHLY_SMTP_USER_NAME"], "SMTP_FROM" => ENV["APPSMOOTHLY_SMTP_FROM"] }
  end

  def deploy_yaml(app)
    lines = []
    lines << "# Generated by appsmoothly — overwritten on every deploy."
    lines << "service: #{app.name}"
    lines << "image: #{app.name}"
    lines << "servers:\n  web:\n    - #{app.prod_server}"
    if Factory.domain
      # Caddy terminates TLS and forwards to kamal-proxy on loopback.
      lines << "proxy:\n  ssl: false\n  forward_headers: true\n  host: #{app.prod_host}"
    else
      lines << "proxy:\n  ssl: true\n  host: #{app.prod_host}"
    end
    # kamal spins up a throwaway registry on this port and tunnels it over ssh
    lines << "registry:\n  server: localhost:5555"
    lines << "builder:\n  arch: amd64"

    secret = %w[RAILS_MASTER_KEY]
    clear = { "SOLID_QUEUE_IN_PUMA" => "true" }
    if app.backups_configured?
      secret += %w[S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY]
      clear.merge!("S3_BUCKET" => app.s3_bucket, "S3_REGION" => app.s3_region_or_default,
                   "S3_ENDPOINT" => app.s3_endpoint_or_default)
    end
    if smtp_clear_env.any?
      secret << "SMTP_PASSWORD"
      clear.merge!(smtp_clear_env)
    end
    lines << ("env:\n  secret:\n" + secret.map { |s| "    - #{s}\n" }.join +
              "  clear:\n" + clear.map { |k, v| "    #{k}: #{v}\n" }.join.chomp)

    lines << %(volumes:\n  - "#{app.name}_storage:/rails/storage")
    lines << "asset_path: /rails/public/assets"

    if app.backups_configured?
      lines << <<~ACC.rstrip
        accessories:
          litestream:
            image: litestream/litestream:0.3
            roles:
              - web
            volumes:
              - "#{app.name}_storage:/rails/storage"
            files:
              - config/litestream.yml:/etc/litestream.yml
            cmd: replicate
            env:
              secret:
                - LITESTREAM_ACCESS_KEY_ID
                - LITESTREAM_SECRET_ACCESS_KEY
              clear:
                LITESTREAM_BUCKET: #{app.s3_bucket}
                LITESTREAM_REGION: #{app.s3_region_or_default}
                LITESTREAM_ENDPOINT: #{app.s3_endpoint_or_default}
      ACC
    end

    lines.join("\n\n") + "\n"
  end

  def env_flags(app)
    env = app.backups_configured? ? app.s3_env : {}
    env = env.merge("SMTP_PASSWORD" => ENV["APPSMOOTHLY_SMTP_PASSWORD"].to_s) if smtp_clear_env.any?
    env.flat_map { |key, value| ["-e", "#{key}=#{value}"] }
  end
end
